import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Getting Started',
      items: [{type: 'autogenerated', dirName: 'module1'}],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation',
      items: [{type: 'autogenerated', dirName: 'module2'}],
    },
    {
      type: 'category',
      label: 'Module 3: Advanced Perception',
      items: [{type: 'autogenerated', dirName: 'module3'}],
    },
    {
      type: 'category',
      label: 'Module 4: Language and Control',
      items: [{type: 'autogenerated', dirName: 'module4'}],
    },
  ],
};

export default sidebars;
